@ECHO OFF
CALL MAIN.bat
ECHO ==============================
ECHO "Start Update 43 Text Files"
ECHO "........Please  Wait........"
ECHO ==============================
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM person WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE person SET pid = (select hn FROM mathhn WHERE person.cid = mathhn.cid and mathhn.cid is not null limit 1)"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE person SET pid = hn WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM service WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE service INNER JOIN person ON service.hn = person.hn SET service.pid = person.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE service SET pid = hn  WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM accident WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE accident INNER JOIN service ON accident.seq = service.seq SET accident.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM accident WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM address WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `address` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE address SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE address INNER JOIN person ON address.hn = person.hn SET address.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `address` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM anc WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE anc INNER JOIN service ON anc.seq = service.seq SET anc.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM anc WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM card WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `card` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE card SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE card INNER JOIN person ON card.hn = person.hn SET card.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `card` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM card WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM charge_opd WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE charge_opd INNER JOIN service ON charge_opd.seq = service.seq SET charge_opd.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM charge_opd WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM chronic WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `chronic` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE chronic SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE chronic INNER JOIN person ON chronic.hn = person.hn SET chronic.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `chronic` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM chronic WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM chronicfu WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE chronicfu INNER JOIN service ON chronicfu.seq = service.seq SET chronicfu.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM chronicfu WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM community_service WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE community_service INNER JOIN service ON community_service.seq = service.seq SET community_service.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM community_service WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM death WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM death WHERE ddeath is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `death` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE death SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE death INNER JOIN person ON death.hn = person.hn SET death.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `death` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM death WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM dental WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE dental INNER JOIN service ON dental.seq = service.seq SET dental.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM dental WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM diagnosis_opd WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE diagnosis_opd INNER JOIN service ON diagnosis_opd.seq = service.seq SET diagnosis_opd.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM diagnosis_opd WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM disability WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `disability` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE disability SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE disability INNER JOIN person ON disability.hn = person.hn SET disability.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `disability` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM disability WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM drugallergy WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `drugallergy` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE drugallergy SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE drugallergy INNER JOIN person ON drugallergy.hn = person.hn SET drugallergy.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `drugallergy` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM drugallergy WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM drug_opd WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE drug_opd INNER JOIN service ON drug_opd.seq = service.seq SET drug_opd.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM drug_opd WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM epi WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `epi` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE epi SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE epi INNER JOIN person ON epi.hn = person.hn SET epi.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `epi` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM epi WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM epi WHERE vaccinetype is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM fp WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE fp INNER JOIN service ON fp.seq = service.seq SET fp.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM fp WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM labfu WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE labfu INNER JOIN service ON labfu.seq = service.seq SET labfu.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM labfu WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM labor WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `labor` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE labor SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE labor INNER JOIN person ON labor.hn = person.hn SET labor.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `labor` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM labor WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM ncdscreen WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE ncdscreen INNER JOIN service ON ncdscreen.seq = service.seq SET ncdscreen.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM ncdscreen WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM newborn WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `newborn` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE newborn SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE newborn INNER JOIN person ON newborn.hn = person.hn SET newborn.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE newborn INNER JOIN person ON newborn.hn = person.hn SET newborn.mpid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `newborn` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM newborn WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM newborncare WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE newborncare INNER JOIN service ON newborncare.seq = service.seq SET newborncare.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM newborncare WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM nutrition WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE nutrition INNER JOIN service ON nutrition.seq = service.seq SET nutrition.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM nutrition WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM postnatal WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE postnatal INNER JOIN service ON postnatal.seq = service.seq SET postnatal.pid = service.pid "
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM postnatal WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM prenatal WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `prenatal` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE prenatal SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE prenatal INNER JOIN person ON prenatal.hn = person.hn SET prenatal.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `prenatal` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM prenatal WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM procedure_opd WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE procedure_opd INNER JOIN service ON procedure_opd.seq = service.seq SET procedure_opd.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM procedure_opd WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM specialpp WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE specialpp INNER JOIN service ON specialpp.seq = service.seq SET specialpp.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM specialpp WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM student WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `student` ADD COLUMN `hn`  varchar(255) NULL AFTER `id`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE student SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE student INNER JOIN person ON student.hn = person.hn SET student.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `student` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `student` DROP COLUMN `id`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM specialpp WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM surveillance WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE surveillance INNER JOIN service ON surveillance.seq = service.seq SET surveillance.pid = service.pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM surveillance WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM women WHERE hospcode !=%HCODE%"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `women` ADD COLUMN `hn`  varchar(255) NULL AFTER `d_update`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE women SET hn = pid"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE women INNER JOIN person ON women.hn = person.hn SET women.pid = person.pid WHERE person.pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "ALTER TABLE `women` DROP COLUMN `hn`"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "DELETE FROM women WHERE pid is null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE person SET hn = pid WHERE pid is not null"
CALL %MYSQL_EXE% --user=%DB_USER% --password=%DB_PWD% -P%DB_PORT% -D%DB_DATA%  -e "UPDATE service SET hn = pid  WHERE pid is not null"

ECHO "Success Update 43 Text Files"
REM PAUSE
CALL 3_Export_43F.bat